### ISSUE TITLE
Obj-c (or swift) cocoapod version?

### ISSUE THREAD

**Issue by rickytribbia** [tink-crypto/tink-cc-gcpkms#1]
Do you have any plan about making an obj-c or swift version of this library distributed via cocoapod? 

Thank you

**Comment by tholenst** [comment]
Not any time soon, I'm sorry. This is very far from being possible for us at the moment. It is already difficult for us to stay up to date with the repositories we have.

We might at some point provide links to other repositories containing Tink integrations, so if someone wants to provide this we would be interested in hearing about it.
